sudo: required
services:
  - docker
before_install:
  - docker build -t mgado1/docker-react ./movies-frontend
  - docker build -t mgado1/docker-backend ./movies-backend
script:
  - echo "skipping tests"
after_success:
  - docker build -t mgado1/docker-react ./movies-frontend
  - docker build -t mgado1/docker-backend ./movies-backend
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mgado1/docker-react
  - docker push mgado1/docker-backend
# delpoy to AWS

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-011135588242'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
