sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react ./movies-frontend
  - docker build -t docker-backend ./movies-backend

after_success: -docker compose up
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-2'
#   app: 'docker-react'
#   env: 'DockerReact-env'
#   bucket_name: 'elasticbeanstalk-us-east-2-123456789'
#   bucket_path: 'docker-react'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
