spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: 
  cloud:
    discovery:
      enabled: false